[package]
name = "asciidocr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.89"
serde = {version ="1.0.210", features=["derive"]}
serde_json = "1.0.128"
tera = "1.20.0"

[dev-dependencies]
assert-json-diff = "2.0.2"
rstest = "0.23.0"
